package com.kosiso.lagosdevelopers.ui

object Constants {

    const val REMOVED_FROM_FAVOURITES = "Removed from favourites"
    const val ADDED_TO_FAVOURITES = "Added to favourites"
    const val REMOVE_FROM_FAVOURITES = "Remove from favourites"
    const val IS_REMOVED_FROM_FAVOURITES = "is removed from favourites"
    const val ADD_TO_FAVOURITES = "Add to favourites"
    const val AVATAR = "avatar"
    const val NAME = "Name:"
    const val EMAIL = "Email:"
    const val BIO = "Bio:"
    const val COMPANY = "Company:"
    const val LOCATION = "Location:"
    const val TWITTER = "Twitter:"
    const val REPOSITORIES = "Repositories:"
    const val FOLLOWERS = "Followers:"
    const val FOLLOWING = "Following:"
    const val DATE_CREATED = "Date Created:"
    const val LAST_UPDATED = "Last Updated:"
    const val INVALID_DATE = "Invalid date"
    const val NO_INTERNET = "No internet connection"
    const val MORE_ICON = "more icon"
    const val FAVOURITES = "Favourites"
    const val DEVELOPERS = "Developers"
    const val DEVELOPER = "Developer"
    const val LAGOS_DEVELOPERS = "Lagos Developers"
    const val  UNABLE_TO_LOAD_DEVELOPERS = "Unable to load developers, enable internet connection and try again."
    const val ERROR_LOADING_MORE_DATA = "Error loading more data"
    const val CHECK_INTERNET_CONNECTION = "Check internet connection and try again"
    const val SEEM_LIKE_YOU_DONT_HAVE_A_FAVOURITE_DEVELOPER = "Seem like you don't have a Favourite developer"
    const val FAVOURITE_DEVELOPERS = "Favourite Developers"
    const val ERROR_LOADING_DATA = "Error loading data, enable internet connection and try again."
    const val CLEAR_FAVOURITE_WARNING = "This would clear all favourites and is not reversible"
    const val CLEAR = "Clear"
    const val FAVOURITE_LIST_CLEARED = "Favourite list is cleared"
    const val CLEAR_FAVOURITES = "Clear all favourites"
    const val ERROR_LOADING_FAVOURITES = "Error loading favourites"
}